# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tommi Israelsson
email: tommi.israelsson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Game Programming student at The Game Assembly stockholm.
  Student Mentor for first year students.
  This is where I put things I've made.
self_description: >-
  <img src="/images/tommi.png"/>
  Contact<br/>
  Mail: <a href="mailto:tommi.israelsson@gmail.com">tommi.israelsson@gmail.com</a><br/>
  Twitter: <a href="https://twitter.com/IsraelssonTommi">IsraelssonTommi</a><br/>
  LinkedIn: <a href="https://www.linkedin.com/in/tommi-israelsson-426832209/">Tommi Israelsson</a><br/>
  Github: <a href="https://github.com/zer0problem">zer0problem</a><br/>
  <br/>
  <a href="/specialization/update/2021/04/09/specialization-final.html">Procedural content generation</a><br/>
  Player interactions<br/>
  Performance<br/>
  Student Mentor<br/>
  <br/>
  <a href="/other/">Other projects</a>

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tommi.israelsson
github_username: zer0problem


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Apply this change to _config.yml file
kramdown:
  hard_wrap: false
  # parse markdown inside block-level HTML tag
  #parse_block_html: true
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
